country_names = {
    "united_states": [
        "AK",
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NC",
        "ND",
        "NE",
        "NH",
        "NJ",
        "NM",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VA",
        "VT",
        "WA",
        "WI",
        "WV",
        "WY",
        "US",
        "USA",
        "United States",
        "Cranberry Township",
        "Woodbridge Township",
        "San Francisco",
        "California",
        "Clarksville",
        "New York",
        "New York City",
        "Cleveland",
        "Connecticut",
        "New Jersey",
        "Arizona",
        "Massachusetts",
    ],
    "canada": [
        "AB",
        "BC",
        "MB",
        "NB",
        "NL",
        "NS",
        "NT",
        "NU",
        "ON",
        "PE",
        "QC",
        "SK",
        "YT",
        "Canada",
        "Newfoundland and Labrador",
        "Nova Scotia",
        "Prince Edward Island",
        "New Brunswick",
        "Quebec",
        "Ontario",
        "Manitoba",
        "Saskatchewan",
        "Alberta",
        "British Columbia",
        "Yukon",
        "Northwest Territories",
        "Nunavut",
    ],
    "united_kingdom": [
        "UK",
        "GB",
        "GBR",
        "United Kingdom",
        "England",
        "Scotland",
        "Wales",
        "Northern Ireland",
        "London",
    ],
    "australia": [
        "AU",
        "AUS",
        "Australia",
    ],
    "india": [
        "IN",
        "India",
    ],
    "germany": [
        "DE",
        "DEU",
        "Germany",
    ],
    "france": [
        "FR",
        "FRA",
        "France",
    ],
    "italy": [
        "IT",
        "ITA",
        "Italy",
    ],
    "spain": [
        "ES",
        "ESP",
        "Spain",
    ],
    "netherlands": ["NL", "NLD", "Netherlands", "The Netherlands"],
    "sweden": [
        "SE",
        "SWE",
        "Sweden",
    ],
    "denmark": [
        "DK",
        "DNK",
        "Denmark",
    ],
    "norway": [
        "NO",
        "NOR",
        "Norway",
    ],
    "finland": [
        "FI",
        "FIN",
        "Finland",
    ],
    "poland": [
        "PL",
        "POL",
        "Poland",
    ],
    "ireland": [
        "IE",
        "IRL",
        "Ireland",
    ],
    "belgium": [
        "BE",
        "BEL",
        "Belgium",
    ],
    "austria": [
        "AT",
        "AUT",
        "Austria",
    ],
    "switzerland": [
        "CH",
        "CHE",
        "Switzerland",
    ],
    "portugal": [
        "PT",
        "PRT",
        "Portugal",
    ],
    "greece": [
        "GR",
        "GRC",
        "Greece",
    ],
    "turkey": [
        "TR",
        "TUR",
        "Turkey",
    ],
    "czech_republic": [
        "CZ",
        "CZE",
        "Czech Republic",
    ],
    "hungary": [
        "HU",
        "HUN",
        "Hungary",
    ],
    "slovakia": [
        "SK",
        "SVK",
        "Slovakia",
    ],
    "romania": [
        "RO",
        "ROU",
        "Romania",
    ],
    "bulgaria": [
        "BG",
        "BGR",
        "Bulgaria",
    ],
    "estonia": [
        "EE",
        "EST",
        "Estonia",
    ],
    "lithuania": [
        "LT",
        "LTU",
        "Lithuania",
    ],
    "latvia": [
        "LV",
        "LVA",
        "Latvia",
    ],
    "slovenia": [
        "SI",
        "SVN",
        "Slovenia",
    ],
    "croatia": [
        "HR",
        "HRV",
        "Croatia",
    ],
    "serbia": [
        "RS",
        "SRB",
        "Serbia",
    ],
    "bosnia_and_herzegovina": [
        "BA",
        "BIH",
        "Bosnia and Herzegovina",
    ],
    "macedonia": [
        "MK",
        "MKD",
        "Macedonia",
    ],
    "albania": [
        "AL",
        "ALB",
        "Albania",
    ],
    "montenegro": [
        "Montenegro",
    ],
    "kosovo": [
        "XK",
        "Kosovo",
    ],
    "malta": [
        "MT",
        "MLT",
        "Malta",
    ],
    "luxembourg": [
        "LU",
        "LUX",
        "Luxembourg",
    ],
    "andorra": [
        "AD",
        "AND",
        "Andorra",
    ],
    "monaco": [
        "MC",
        "MCO",
        "Monaco",
    ],
    "san_marino": [
        "SM",
        "SMR",
        "San Marino",
    ],
    "vatican_city": [
        "Vatican City",
    ],
}
